config/routes.rb
Cheqit::Application.routes.draw do
  resources :users do
    member do
      get :cheqeds
    end
  end
  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  match 'search',   :to => 'users#search'

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<%= link_to "about", about_path %> | <%= link_to "contact", contact_path %> | <%= link_to "help", help_path %>

app/views/layouts/_header.html.erb
<% if signed_in? %>
	<ul><li><%= link_to "browse", users_path %></li>
		<li><%= link_to "profile", current_user %></li>
		<li><%= link_to "cheqs", cheqeds_user_path(current_user) %></li>
		<!--<li><%= link_to "settings", edit_user_path(current_user) %></li>-->
		<li><%= link_to "log out", signout_path, :method => :delete %></li>
	</ul>
<% else %>
	<%= form_for(:session, :url => sessions_path) do |f| %>
		<%= f.text_field :email %>
		<%= f.password_field :password %>
		<%= f.submit "log in" %>
	<% end %>
<% end %>
<h1><a href="/"><span>cheq</span>.it</a></h1>

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
		<title><%= title %></title>
		<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
		<link rel="stylesheet" type="text/css" href="/cheq.css">
		<%= csrf_meta_tag %>
		<%= javascript_include_tag :defaults %>
	</head>
	<body>
		<div id="header">
			<%= render 'layouts/header' %>
		</div>
		<div id="content">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, :class => "flash #{key}") %>
			<% end %>
			<%= yield %>
			<div style='clear:both'></div>
		</div>
		<div id="footer">
			<%= render 'layouts/footer' %>
			<!--<%= debug(params) if Rails.env.development? %>-->
		</div>
	</body>
</html>